// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayService(r []*Service, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeService(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayServiceWrapper struct {
	Target *[]*Service
}

func (_ *ArrayServiceWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayServiceWrapper) Finalize()                        {}
func (_ *ArrayServiceWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayServiceWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayServiceWrapper) AppendArray() types.Field {
	var v *Service
	v = NewService()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
