// Package sfgo implements Go stubs for the SysFlow format.
package sfgo

// SFObjectType defines the type for the SysFlow object type.
type SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnum

// SFObjectType enumeration.
const (
	SF_HEADER    SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumSFHeader
	SF_CONT      SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumContainer
	SF_PROCESS   SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumProcess
	SF_FILE      SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumFile
	SF_PROC_EVT  SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumProcessEvent
	SF_PROC_FLOW SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumProcessFlow
	SF_NET_FLOW  SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumNetworkFlow
	SF_FILE_FLOW SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumFileFlow
	SF_FILE_EVT  SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumFileEvent
	SF_NET_EVT   SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumNetworkEvent
	SF_K8S_POD   SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumPod
	SF_K8S_EVT   SFObjectType = UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventProcessFlowPodK8sEventTypeEnumK8sEvent
)
