// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type ContainerIdUnionTypeEnum int

const (
	ContainerIdUnionTypeEnumString ContainerIdUnionTypeEnum = 1
)

type ContainerIdUnion struct {
	Null      *types.NullVal
	String    string
	UnionType ContainerIdUnionTypeEnum
}

func writeContainerIdUnion(r *ContainerIdUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case ContainerIdUnionTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for *ContainerIdUnion")
}

func NewContainerIdUnion() *ContainerIdUnion {
	return &ContainerIdUnion{}
}

func (_ *ContainerIdUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *ContainerIdUnion) SetLong(v int64) {
	r.UnionType = (ContainerIdUnionTypeEnum)(v)
}
func (r *ContainerIdUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ *ContainerIdUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *ContainerIdUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *ContainerIdUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ContainerIdUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *ContainerIdUnion) Finalize()                        {}

func (r *ContainerIdUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case ContainerIdUnionTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for *ContainerIdUnion")
}

func (r *ContainerIdUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for *ContainerIdUnion")
}
