// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type FeUnionTypeEnum int

const (
	FeUnionTypeEnumFileEvent FeUnionTypeEnum = 1
)

type FeUnion struct {
	Null      *types.NullVal
	FileEvent *FileEvent
	UnionType FeUnionTypeEnum
}

func writeFeUnion(r *FeUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case FeUnionTypeEnumFileEvent:
		return writeFileEvent(r.FileEvent, w)
	}
	return fmt.Errorf("invalid value for *FeUnion")
}

func NewFeUnion() *FeUnion {
	return &FeUnion{}
}

func (_ *FeUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *FeUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *FeUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *FeUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *FeUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *FeUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *FeUnion) SetLong(v int64) {
	r.UnionType = (FeUnionTypeEnum)(v)
}
func (r *FeUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.FileEvent = NewFileEvent()
		return r.FileEvent
	}
	panic("Unknown field index")
}
func (_ *FeUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *FeUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *FeUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *FeUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *FeUnion) Finalize()                        {}

func (r *FeUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case FeUnionTypeEnumFileEvent:
		return json.Marshal(map[string]interface{}{"FileEvent": r.FileEvent})
	}
	return nil, fmt.Errorf("invalid value for *FeUnion")
}

func (r *FeUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["FileEvent"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FileEvent)
	}
	return fmt.Errorf("invalid value for *FeUnion")
}
