// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type FileUnionTypeEnum int

const (
	FileUnionTypeEnumFile FileUnionTypeEnum = 1
)

type FileUnion struct {
	Null      *types.NullVal
	File      *File
	UnionType FileUnionTypeEnum
}

func writeFileUnion(r *FileUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case FileUnionTypeEnumFile:
		return writeFile(r.File, w)
	}
	return fmt.Errorf("invalid value for *FileUnion")
}

func NewFileUnion() *FileUnion {
	return &FileUnion{}
}

func (_ *FileUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *FileUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *FileUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *FileUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *FileUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *FileUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *FileUnion) SetLong(v int64) {
	r.UnionType = (FileUnionTypeEnum)(v)
}
func (r *FileUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.File = NewFile()
		return r.File
	}
	panic("Unknown field index")
}
func (_ *FileUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *FileUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *FileUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *FileUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *FileUnion) Finalize()                        {}

func (r *FileUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case FileUnionTypeEnumFile:
		return json.Marshal(map[string]interface{}{"File": r.File})
	}
	return nil, fmt.Errorf("invalid value for *FileUnion")
}

func (r *FileUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["File"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.File)
	}
	return fmt.Errorf("invalid value for *FileUnion")
}
