// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
	"io"
)

type FileFlow struct {
	ProcOID *OID `json:"procOID"`

	Ts int64 `json:"ts"`

	Tid int64 `json:"tid"`

	OpFlags int32 `json:"opFlags"`

	OpenFlags int32 `json:"openFlags"`

	EndTs int64 `json:"endTs"`

	FileOID FOID `json:"fileOID"`

	Fd int32 `json:"fd"`

	NumRRecvOps int64 `json:"numRRecvOps"`

	NumWSendOps int64 `json:"numWSendOps"`

	NumRRecvBytes int64 `json:"numRRecvBytes"`

	NumWSendBytes int64 `json:"numWSendBytes"`
}

const FileFlowAvroCRC64Fingerprint = "\xb0\x9a\xb1-\x80\x85G\\"

func NewFileFlow() *FileFlow {
	return &FileFlow{}
}

func DeserializeFileFlow(r io.Reader) (*FileFlow, error) {
	t := NewFileFlow()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeFileFlowFromSchema(r io.Reader, schema string) (*FileFlow, error) {
	t := NewFileFlow()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeFileFlow(r *FileFlow, w io.Writer) error {
	var err error
	err = writeOID(r.ProcOID, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Ts, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Tid, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.OpFlags, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.OpenFlags, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.EndTs, w)
	if err != nil {
		return err
	}
	err = writeFOID(r.FileOID, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Fd, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.NumRRecvOps, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.NumWSendOps, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.NumRRecvBytes, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.NumWSendBytes, w)
	if err != nil {
		return err
	}
	return err
}

func (r *FileFlow) Serialize(w io.Writer) error {
	return writeFileFlow(r, w)
}

func (r *FileFlow) Schema() string {
	return "{\"fields\":[{\"name\":\"procOID\",\"type\":{\"fields\":[{\"name\":\"createTS\",\"type\":\"long\"},{\"name\":\"hpid\",\"type\":\"long\"}],\"name\":\"OID\",\"namespace\":\"sysflow.type\",\"type\":\"record\"}},{\"name\":\"ts\",\"type\":\"long\"},{\"name\":\"tid\",\"type\":\"long\"},{\"name\":\"opFlags\",\"type\":\"int\"},{\"name\":\"openFlags\",\"type\":\"int\"},{\"name\":\"endTs\",\"type\":\"long\"},{\"name\":\"fileOID\",\"type\":{\"name\":\"FOID\",\"namespace\":\"sysflow.type\",\"size\":20,\"type\":\"fixed\"}},{\"name\":\"fd\",\"type\":\"int\"},{\"name\":\"numRRecvOps\",\"type\":\"long\"},{\"name\":\"numWSendOps\",\"type\":\"long\"},{\"name\":\"numRRecvBytes\",\"type\":\"long\"},{\"name\":\"numWSendBytes\",\"type\":\"long\"}],\"name\":\"sysflow.flow.FileFlow\",\"type\":\"record\"}"
}

func (r *FileFlow) SchemaName() string {
	return "sysflow.flow.FileFlow"
}

func (_ *FileFlow) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *FileFlow) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *FileFlow) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *FileFlow) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *FileFlow) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *FileFlow) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *FileFlow) SetString(v string)   { panic("Unsupported operation") }
func (_ *FileFlow) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *FileFlow) Get(i int) types.Field {
	switch i {
	case 0:
		r.ProcOID = NewOID()

		return r.ProcOID
	case 1:
		return &types.Long{Target: &r.Ts}
	case 2:
		return &types.Long{Target: &r.Tid}
	case 3:
		return &types.Int{Target: &r.OpFlags}
	case 4:
		return &types.Int{Target: &r.OpenFlags}
	case 5:
		return &types.Long{Target: &r.EndTs}
	case 6:
		return &FOIDWrapper{Target: &r.FileOID}
	case 7:
		return &types.Int{Target: &r.Fd}
	case 8:
		return &types.Long{Target: &r.NumRRecvOps}
	case 9:
		return &types.Long{Target: &r.NumWSendOps}
	case 10:
		return &types.Long{Target: &r.NumRRecvBytes}
	case 11:
		return &types.Long{Target: &r.NumWSendBytes}
	}
	panic("Unknown field index")
}

func (r *FileFlow) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *FileFlow) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ *FileFlow) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *FileFlow) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *FileFlow) Finalize()                        {}

func (_ *FileFlow) AvroCRC64Fingerprint() []byte {
	return []byte(FileFlowAvroCRC64Fingerprint)
}
