// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewFileFlowWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewFileFlow()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type FileFlowReader struct {
	r io.Reader
	p *vm.Program
}

func NewFileFlowReader(r io.Reader) (*FileFlowReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewFileFlow()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &FileFlowReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r FileFlowReader) Read() (*FileFlow, error) {
	t := NewFileFlow()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
