// Package sfgo implements Go stubs for the SysFlow format.
package sfgo

// Extended constants for multi-source record
const (
	// Extended operations
	OP_PTRACE = (1 << 21)

	// Extended Process s
	PROC_GUID_STR                = 0
	PROC_IMAGE_STR               = 1
	PROC_CURR_DIRECTORY_STR      = 2
	PROC_LOGON_GUID_STR          = 3
	PROC_LOGON_ID_STR            = 4
	PROC_TERMINAL_SESSION_ID_STR = 5
	PROC_INTEGRITY_LEVEL_STR     = 6
	PROC_SIGNATURE_STR           = 7
	PROC_SIGNATURE_STATUS_STR    = 8
	PROC_SHA1_HASH_STR           = 9
	PROC_MD5_HASH_STR            = 10
	PROC_SHA256_HASH_STR         = 11
	PROC_IMP_HASH_STR            = 12
	NUM_EXT_PROC_ATTRS_STR       = PROC_IMP_HASH_STR + 1

	PROC_SIGNED_INT        = 0
	NUM_EXT_PROC_ATTRS_INT = PROC_SIGNED_INT + 1

	// Extended File s
	FILE_SHA1_HASH_STR        = 0
	FILE_MD5_HASH_STR         = 1
	FILE_SHA256_HASH_STR      = 2
	FILE_IMP_HASH_STR         = 3
	FILE_SIGNATURE_STR        = 4
	FILE_SIGNATURE_STATUS_STR = 5
	FILE_DETAILS_STR          = 6
	NUM_EXT_FILE_STR          = FILE_DETAILS_STR + 1

	FILE_SIGNED_INT  = 0
	NUM_EXT_FILE_INT = FILE_SIGNED_INT + 1

	// Extended Network s
	NET_SOURCE_HOST_NAME_STR = 0
	NET_SOURCE_PORT_NAME_STR = 1
	NET_DEST_HOST_NAME_STR   = 2
	NET_DEST_PORT_NAME_STR   = 3
	NUM_EXT_NET_STR          = NET_DEST_PORT_NAME_STR + 1

	//Extended Event s include the attributes for a process +
	EVT_TARG_PROC_STATE_INT              = 0
	EVT_TARG_PROC_OID_CREATETS_INT       = EVT_TARG_PROC_STATE_INT + 1
	EVT_TARG_PROC_OID_HPID_INT           = EVT_TARG_PROC_OID_CREATETS_INT + 1
	EVT_TARG_PROC_POID_CREATETS_INT      = EVT_TARG_PROC_OID_HPID_INT + 1
	EVT_TARG_PROC_POID_HPID_INT          = EVT_TARG_PROC_POID_CREATETS_INT + 1
	EVT_TARG_PROC_TS_INT                 = EVT_TARG_PROC_POID_HPID_INT + 1
	EVT_TARG_PROC_EXE_STR                = 0
	EVT_TARG_PROC_EXEARGS_STR            = EVT_TARG_PROC_EXE_STR + 1
	EVT_TARG_PROC_UID_INT                = EVT_TARG_PROC_TS_INT + 1
	EVT_TARG_PROC_USERNAME_STR           = EVT_TARG_PROC_EXEARGS_STR + 1
	EVT_TARG_PROC_GID_INT                = EVT_TARG_PROC_UID_INT + 1
	EVT_TARG_PROC_GROUPNAME_STR          = EVT_TARG_PROC_USERNAME_STR + 1
	EVT_TARG_PROC_TTY_INT                = EVT_TARG_PROC_GID_INT + 1
	EVT_TARG_PROC_CONTAINERID_STRING_STR = EVT_TARG_PROC_GROUPNAME_STR + 1
	EVT_TARG_PROC_ENTRY_INT              = EVT_TARG_PROC_TTY_INT + 1

	EVT_TARG_PROC_GUID_STR                = EVT_TARG_PROC_ENTRY_INT + 1
	EVT_TARG_PROC_IMAGE_STR               = EVT_TARG_PROC_GUID_STR + 1
	EVT_TARG_PROC_CURR_DIRECTORY_STR      = EVT_TARG_PROC_IMAGE_STR + 1
	EVT_TARG_PROC_LOGON_GUID_STR          = EVT_TARG_PROC_CURR_DIRECTORY_STR + 1
	EVT_TARG_PROC_LOGON_ID_STR            = EVT_TARG_PROC_LOGON_GUID_STR + 1
	EVT_TARG_PROC_TERMINAL_SESSION_ID_STR = EVT_TARG_PROC_LOGON_ID_STR + 1
	EVT_TARG_PROC_INTEGRITY_LEVEL_STR     = EVT_TARG_PROC_TERMINAL_SESSION_ID_STR + 1
	EVT_TARG_PROC_SIGNATURE_STR           = EVT_TARG_PROC_INTEGRITY_LEVEL_STR + 1
	EVT_TARG_PROC_SIGNATURE_STATUS_STR    = EVT_TARG_PROC_SIGNATURE_STR + 1
	EVT_TARG_PROC_SHA1_HASH_STR           = EVT_TARG_PROC_SIGNATURE_STATUS_STR + 1
	EVT_TARG_PROC_MD5_HASH_STR            = EVT_TARG_PROC_SHA1_HASH_STR + 1
	EVT_TARG_PROC_SHA256_HASH_STR         = EVT_TARG_PROC_MD5_HASH_STR + 1
	EVT_TARG_PROC_IMP_HASH_STR            = EVT_TARG_PROC_SHA256_HASH_STR + 1
	EVT_TARG_PROC_START_ADDR_STR          = EVT_TARG_PROC_IMP_HASH_STR + 1
	EVT_TARG_PROC_START_MODULE_STR        = EVT_TARG_PROC_START_ADDR_STR + 1
	EVT_TARG_PROC_START_FUNCTION_STR      = EVT_TARG_PROC_START_MODULE_STR + 1
	EVT_TARG_PROC_GRANT_ACCESS_STR        = EVT_TARG_PROC_START_FUNCTION_STR + 1
	EVT_TARG_PROC_CALL_TRACE_STR          = EVT_TARG_PROC_GRANT_ACCESS_STR + 1
	EVT_TARG_PROC_ACCESS_TYPE_STR         = EVT_TARG_PROC_CALL_TRACE_STR + 1

	EVT_TARG_PROC_SIGNED_INT        = EVT_TARG_PROC_ENTRY_INT + 1
	EVT_TARG_PROC_NEW_THREAD_ID_INT = EVT_TARG_PROC_SIGNED_INT + 1

	NUM_EXT_EVT_STR = EVT_TARG_PROC_ACCESS_TYPE_STR + 1
	NUM_EXT_EVT_INT = EVT_TARG_PROC_NEW_THREAD_ID_INT + 1

	// Indexes into enriched flat record
	SYSFLOW_IDX = 0
	PROC_IDX    = 1
	FILE_IDX    = 2
	NETWORK_IDX = 3

	// Hash indexes for the hash parsing
	SHA1_HASH_STR   = 0
	MD5_HASH_STR    = 1
	SHA256_HASH_STR = 2
	IMP_HASH_STR    = 3

	// Data Sources
	SYSFLOW_SRC   Source = 0
	PROCESS_SRC   Source = 1
	FILE_SRC      Source = 2
	NETWORK_SRC   Source = 3
	TARG_PROC_SRC Source = 4
)
