// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"github.com/actgardner/gogen-avro/v7/vm/types"
	"io"
)

func writeFOID(r FOID, w io.Writer) error {
	_, err := w.Write(r[:])
	return err
}

type FOIDWrapper struct {
	Target *FOID
}

type FOID [20]byte

func (_ *FOIDWrapper) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *FOIDWrapper) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *FOIDWrapper) SetLong(v int64)     { panic("Unsupported operation") }
func (_ *FOIDWrapper) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *FOIDWrapper) SetDouble(v float64) { panic("Unsupported operation") }
func (r *FOIDWrapper) SetBytes(v []byte) {
	copy((*r.Target)[:], v)
}
func (_ *FOIDWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *FOIDWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *FOIDWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *FOIDWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *FOIDWrapper) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *FOIDWrapper) NullField(int)                    { panic("Unsupported operation") }
func (_ *FOIDWrapper) Finalize()                        {}
func (_ *FOIDWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
