// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type NeUnionTypeEnum int

const (
	NeUnionTypeEnumNetworkEvent NeUnionTypeEnum = 1
)

type NeUnion struct {
	Null         *types.NullVal
	NetworkEvent *NetworkEvent
	UnionType    NeUnionTypeEnum
}

func writeNeUnion(r *NeUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case NeUnionTypeEnumNetworkEvent:
		return writeNetworkEvent(r.NetworkEvent, w)
	}
	return fmt.Errorf("invalid value for *NeUnion")
}

func NewNeUnion() *NeUnion {
	return &NeUnion{}
}

func (_ *NeUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *NeUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *NeUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *NeUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *NeUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *NeUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *NeUnion) SetLong(v int64) {
	r.UnionType = (NeUnionTypeEnum)(v)
}
func (r *NeUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.NetworkEvent = NewNetworkEvent()
		return r.NetworkEvent
	}
	panic("Unknown field index")
}
func (_ *NeUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *NeUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *NeUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *NeUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *NeUnion) Finalize()                        {}

func (r *NeUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case NeUnionTypeEnumNetworkEvent:
		return json.Marshal(map[string]interface{}{"NetworkEvent": r.NetworkEvent})
	}
	return nil, fmt.Errorf("invalid value for *NeUnion")
}

func (r *NeUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["NetworkEvent"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.NetworkEvent)
	}
	return fmt.Errorf("invalid value for *NeUnion")
}
