// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewNetworkFlowWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewNetworkFlow()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type NetworkFlowReader struct {
	r io.Reader
	p *vm.Program
}

func NewNetworkFlowReader(r io.Reader) (*NetworkFlowReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewNetworkFlow()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &NetworkFlowReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r NetworkFlowReader) Read() (*NetworkFlow, error) {
	t := NewNetworkFlow()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
