// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type NewFileOIDUnionTypeEnum int

const (
	NewFileOIDUnionTypeEnumFOID NewFileOIDUnionTypeEnum = 1
)

type NewFileOIDUnion struct {
	Null      *types.NullVal
	FOID      FOID
	UnionType NewFileOIDUnionTypeEnum
}

func writeNewFileOIDUnion(r *NewFileOIDUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case NewFileOIDUnionTypeEnumFOID:
		return writeFOID(r.FOID, w)
	}
	return fmt.Errorf("invalid value for *NewFileOIDUnion")
}

func NewNewFileOIDUnion() *NewFileOIDUnion {
	return &NewFileOIDUnion{}
}

func (_ *NewFileOIDUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *NewFileOIDUnion) SetLong(v int64) {
	r.UnionType = (NewFileOIDUnionTypeEnum)(v)
}
func (r *NewFileOIDUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &FOIDWrapper{Target: (&r.FOID)}
	}
	panic("Unknown field index")
}
func (_ *NewFileOIDUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *NewFileOIDUnion) Finalize()                        {}

func (r *NewFileOIDUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case NewFileOIDUnionTypeEnumFOID:
		return json.Marshal(map[string]interface{}{"FOID": r.FOID})
	}
	return nil, fmt.Errorf("invalid value for *NewFileOIDUnion")
}

func (r *NewFileOIDUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["FOID"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FOID)
	}
	return fmt.Errorf("invalid value for *NewFileOIDUnion")
}
