// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type NewfileUnionTypeEnum int

const (
	NewfileUnionTypeEnumFile NewfileUnionTypeEnum = 1
)

type NewfileUnion struct {
	Null      *types.NullVal
	File      *File
	UnionType NewfileUnionTypeEnum
}

func writeNewfileUnion(r *NewfileUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case NewfileUnionTypeEnumFile:
		return writeFile(r.File, w)
	}
	return fmt.Errorf("invalid value for *NewfileUnion")
}

func NewNewfileUnion() *NewfileUnion {
	return &NewfileUnion{}
}

func (_ *NewfileUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *NewfileUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *NewfileUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *NewfileUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *NewfileUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *NewfileUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *NewfileUnion) SetLong(v int64) {
	r.UnionType = (NewfileUnionTypeEnum)(v)
}
func (r *NewfileUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.File = NewFile()
		return r.File
	}
	panic("Unknown field index")
}
func (_ *NewfileUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *NewfileUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *NewfileUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *NewfileUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *NewfileUnion) Finalize()                        {}

func (r *NewfileUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case NewfileUnionTypeEnumFile:
		return json.Marshal(map[string]interface{}{"File": r.File})
	}
	return nil, fmt.Errorf("invalid value for *NewfileUnion")
}

func (r *NewfileUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["File"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.File)
	}
	return fmt.Errorf("invalid value for *NewfileUnion")
}
