// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type PeUnionTypeEnum int

const (
	PeUnionTypeEnumProcessEvent PeUnionTypeEnum = 1
)

type PeUnion struct {
	Null         *types.NullVal
	ProcessEvent *ProcessEvent
	UnionType    PeUnionTypeEnum
}

func writePeUnion(r *PeUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case PeUnionTypeEnumProcessEvent:
		return writeProcessEvent(r.ProcessEvent, w)
	}
	return fmt.Errorf("invalid value for *PeUnion")
}

func NewPeUnion() *PeUnion {
	return &PeUnion{}
}

func (_ *PeUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *PeUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *PeUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *PeUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *PeUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *PeUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *PeUnion) SetLong(v int64) {
	r.UnionType = (PeUnionTypeEnum)(v)
}
func (r *PeUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.ProcessEvent = NewProcessEvent()
		return r.ProcessEvent
	}
	panic("Unknown field index")
}
func (_ *PeUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *PeUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *PeUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *PeUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *PeUnion) Finalize()                        {}

func (r *PeUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case PeUnionTypeEnumProcessEvent:
		return json.Marshal(map[string]interface{}{"ProcessEvent": r.ProcessEvent})
	}
	return nil, fmt.Errorf("invalid value for *PeUnion")
}

func (r *PeUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["ProcessEvent"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ProcessEvent)
	}
	return fmt.Errorf("invalid value for *PeUnion")
}
