// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     GraphletRecord.avsc
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type PfUnionTypeEnum int

const (
	PfUnionTypeEnumProcessFlow PfUnionTypeEnum = 1
)

type PfUnion struct {
	Null        *types.NullVal
	ProcessFlow *ProcessFlow
	UnionType   PfUnionTypeEnum
}

func writePfUnion(r *PfUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case PfUnionTypeEnumProcessFlow:
		return writeProcessFlow(r.ProcessFlow, w)
	}
	return fmt.Errorf("invalid value for *PfUnion")
}

func NewPfUnion() *PfUnion {
	return &PfUnion{}
}

func (_ *PfUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *PfUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *PfUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *PfUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *PfUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *PfUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *PfUnion) SetLong(v int64) {
	r.UnionType = (PfUnionTypeEnum)(v)
}
func (r *PfUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.ProcessFlow = NewProcessFlow()
		return r.ProcessFlow
	}
	panic("Unknown field index")
}
func (_ *PfUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *PfUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *PfUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *PfUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *PfUnion) Finalize()                        {}

func (r *PfUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case PfUnionTypeEnumProcessFlow:
		return json.Marshal(map[string]interface{}{"ProcessFlow": r.ProcessFlow})
	}
	return nil, fmt.Errorf("invalid value for *PfUnion")
}

func (r *PfUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["ProcessFlow"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ProcessFlow)
	}
	return fmt.Errorf("invalid value for *PfUnion")
}
