// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type PodIdUnionTypeEnum int

const (
	PodIdUnionTypeEnumString PodIdUnionTypeEnum = 1
)

type PodIdUnion struct {
	Null      *types.NullVal
	String    string
	UnionType PodIdUnionTypeEnum
}

func writePodIdUnion(r *PodIdUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case PodIdUnionTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for *PodIdUnion")
}

func NewPodIdUnion() *PodIdUnion {
	return &PodIdUnion{}
}

func (_ *PodIdUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *PodIdUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *PodIdUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *PodIdUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *PodIdUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *PodIdUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *PodIdUnion) SetLong(v int64) {
	r.UnionType = (PodIdUnionTypeEnum)(v)
}
func (r *PodIdUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ *PodIdUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *PodIdUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *PodIdUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *PodIdUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *PodIdUnion) Finalize()                        {}

func (r *PodIdUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case PodIdUnionTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for *PodIdUnion")
}

func (r *PodIdUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for *PodIdUnion")
}
