// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type RecUnionTypeEnum int

const (
	RecUnionTypeEnumSFHeader RecUnionTypeEnum = 0

	RecUnionTypeEnumContainer RecUnionTypeEnum = 1

	RecUnionTypeEnumProcess RecUnionTypeEnum = 2

	RecUnionTypeEnumFile RecUnionTypeEnum = 3

	RecUnionTypeEnumProcessEvent RecUnionTypeEnum = 4

	RecUnionTypeEnumNetworkFlow RecUnionTypeEnum = 5

	RecUnionTypeEnumFileFlow RecUnionTypeEnum = 6

	RecUnionTypeEnumFileEvent RecUnionTypeEnum = 7

	RecUnionTypeEnumNetworkEvent RecUnionTypeEnum = 8

	RecUnionTypeEnumProcessFlow RecUnionTypeEnum = 9

	RecUnionTypeEnumPod RecUnionTypeEnum = 10

	RecUnionTypeEnumK8sEvent RecUnionTypeEnum = 11
)

type RecUnion struct {
	SFHeader     *SFHeader
	Container    *Container
	Process      *Process
	File         *File
	ProcessEvent *ProcessEvent
	NetworkFlow  *NetworkFlow
	FileFlow     *FileFlow
	FileEvent    *FileEvent
	NetworkEvent *NetworkEvent
	ProcessFlow  *ProcessFlow
	Pod          *Pod
	K8sEvent     *K8sEvent
	UnionType    RecUnionTypeEnum
}

func writeRecUnion(r *RecUnion, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case RecUnionTypeEnumSFHeader:
		return writeSFHeader(r.SFHeader, w)
	case RecUnionTypeEnumContainer:
		return writeContainer(r.Container, w)
	case RecUnionTypeEnumProcess:
		return writeProcess(r.Process, w)
	case RecUnionTypeEnumFile:
		return writeFile(r.File, w)
	case RecUnionTypeEnumProcessEvent:
		return writeProcessEvent(r.ProcessEvent, w)
	case RecUnionTypeEnumNetworkFlow:
		return writeNetworkFlow(r.NetworkFlow, w)
	case RecUnionTypeEnumFileFlow:
		return writeFileFlow(r.FileFlow, w)
	case RecUnionTypeEnumFileEvent:
		return writeFileEvent(r.FileEvent, w)
	case RecUnionTypeEnumNetworkEvent:
		return writeNetworkEvent(r.NetworkEvent, w)
	case RecUnionTypeEnumProcessFlow:
		return writeProcessFlow(r.ProcessFlow, w)
	case RecUnionTypeEnumPod:
		return writePod(r.Pod, w)
	case RecUnionTypeEnumK8sEvent:
		return writeK8sEvent(r.K8sEvent, w)
	}
	return fmt.Errorf("invalid value for *RecUnion")
}

func NewRecUnion() *RecUnion {
	return &RecUnion{}
}

func (_ *RecUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *RecUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *RecUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *RecUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RecUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *RecUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *RecUnion) SetLong(v int64) {
	r.UnionType = (RecUnionTypeEnum)(v)
}
func (r *RecUnion) Get(i int) types.Field {
	switch i {
	case 0:
		r.SFHeader = NewSFHeader()
		return r.SFHeader
	case 1:
		r.Container = NewContainer()
		return r.Container
	case 2:
		r.Process = NewProcess()
		return r.Process
	case 3:
		r.File = NewFile()
		return r.File
	case 4:
		r.ProcessEvent = NewProcessEvent()
		return r.ProcessEvent
	case 5:
		r.NetworkFlow = NewNetworkFlow()
		return r.NetworkFlow
	case 6:
		r.FileFlow = NewFileFlow()
		return r.FileFlow
	case 7:
		r.FileEvent = NewFileEvent()
		return r.FileEvent
	case 8:
		r.NetworkEvent = NewNetworkEvent()
		return r.NetworkEvent
	case 9:
		r.ProcessFlow = NewProcessFlow()
		return r.ProcessFlow
	case 10:
		r.Pod = NewPod()
		return r.Pod
	case 11:
		r.K8sEvent = NewK8sEvent()
		return r.K8sEvent
	}
	panic("Unknown field index")
}
func (_ *RecUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *RecUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *RecUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RecUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *RecUnion) Finalize()                        {}

func (r *RecUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case RecUnionTypeEnumSFHeader:
		return json.Marshal(map[string]interface{}{"SFHeader": r.SFHeader})
	case RecUnionTypeEnumContainer:
		return json.Marshal(map[string]interface{}{"Container": r.Container})
	case RecUnionTypeEnumProcess:
		return json.Marshal(map[string]interface{}{"Process": r.Process})
	case RecUnionTypeEnumFile:
		return json.Marshal(map[string]interface{}{"File": r.File})
	case RecUnionTypeEnumProcessEvent:
		return json.Marshal(map[string]interface{}{"ProcessEvent": r.ProcessEvent})
	case RecUnionTypeEnumNetworkFlow:
		return json.Marshal(map[string]interface{}{"NetworkFlow": r.NetworkFlow})
	case RecUnionTypeEnumFileFlow:
		return json.Marshal(map[string]interface{}{"FileFlow": r.FileFlow})
	case RecUnionTypeEnumFileEvent:
		return json.Marshal(map[string]interface{}{"FileEvent": r.FileEvent})
	case RecUnionTypeEnumNetworkEvent:
		return json.Marshal(map[string]interface{}{"NetworkEvent": r.NetworkEvent})
	case RecUnionTypeEnumProcessFlow:
		return json.Marshal(map[string]interface{}{"ProcessFlow": r.ProcessFlow})
	case RecUnionTypeEnumPod:
		return json.Marshal(map[string]interface{}{"Pod": r.Pod})
	case RecUnionTypeEnumK8sEvent:
		return json.Marshal(map[string]interface{}{"K8sEvent": r.K8sEvent})
	}
	return nil, fmt.Errorf("invalid value for *RecUnion")
}

func (r *RecUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["SFHeader"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.SFHeader)
	}
	if value, ok := fields["Container"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Container)
	}
	if value, ok := fields["Process"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Process)
	}
	if value, ok := fields["File"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.File)
	}
	if value, ok := fields["ProcessEvent"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.ProcessEvent)
	}
	if value, ok := fields["NetworkFlow"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.NetworkFlow)
	}
	if value, ok := fields["FileFlow"]; ok {
		r.UnionType = 6
		return json.Unmarshal([]byte(value), &r.FileFlow)
	}
	if value, ok := fields["FileEvent"]; ok {
		r.UnionType = 7
		return json.Unmarshal([]byte(value), &r.FileEvent)
	}
	if value, ok := fields["NetworkEvent"]; ok {
		r.UnionType = 8
		return json.Unmarshal([]byte(value), &r.NetworkEvent)
	}
	if value, ok := fields["ProcessFlow"]; ok {
		r.UnionType = 9
		return json.Unmarshal([]byte(value), &r.ProcessFlow)
	}
	if value, ok := fields["Pod"]; ok {
		r.UnionType = 10
		return json.Unmarshal([]byte(value), &r.Pod)
	}
	if value, ok := fields["K8sEvent"]; ok {
		r.UnionType = 11
		return json.Unmarshal([]byte(value), &r.K8sEvent)
	}
	return fmt.Errorf("invalid value for *RecUnion")
}
