// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionNullFOIDTypeEnum int

const (
	UnionNullFOIDTypeEnumFOID UnionNullFOIDTypeEnum = 1
)

type UnionNullFOID struct {
	Null      *types.NullVal
	FOID      FOID
	UnionType UnionNullFOIDTypeEnum
}

func writeUnionNullFOID(r *UnionNullFOID, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullFOIDTypeEnumFOID:
		return writeFOID(r.FOID, w)
	}
	return fmt.Errorf("invalid value for *UnionNullFOID")
}

func NewUnionNullFOID() *UnionNullFOID {
	return &UnionNullFOID{}
}

func (_ *UnionNullFOID) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetString(v string)  { panic("Unsupported operation") }
func (r *UnionNullFOID) SetLong(v int64) {
	r.UnionType = (UnionNullFOIDTypeEnum)(v)
}
func (r *UnionNullFOID) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &FOIDWrapper{Target: (&r.FOID)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullFOID) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullFOID) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFOID) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullFOID) Finalize()                        {}

func (r *UnionNullFOID) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionNullFOIDTypeEnumFOID:
		return json.Marshal(map[string]interface{}{"FOID": r.FOID})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullFOID")
}

func (r *UnionNullFOID) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["FOID"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FOID)
	}
	return fmt.Errorf("invalid value for *UnionNullFOID")
}
