// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionNullFOIDTypeEnum int

const (
	UnionNullFOIDTypeEnumFOID UnionNullFOIDTypeEnum = 1
)

type UnionNullFOID struct {
	Null      *types.NullVal
	FOID      FOID
	UnionType UnionNullFOIDTypeEnum
}

func writeUnionNullFOID(r *UnionNullFOID, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullFOIDTypeEnumFOID:
		return writeFOID(r.FOID, w)
	}
	return fmt.Errorf("invalid value for *UnionNullFOID")
}

func NewUnionNullFOID() *UnionNullFOID {
	return &UnionNullFOID{}
}

func (r *UnionNullFOID) Serialize(w io.Writer) error {
	return writeUnionNullFOID(r, w)
}

func DeserializeUnionNullFOID(r io.Reader) (*UnionNullFOID, error) {
	t := NewUnionNullFOID()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullFOIDFromSchema(r io.Reader, schema string) (*UnionNullFOID, error) {
	t := NewUnionNullFOID()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullFOID) Schema() string {
	return "[\"null\",{\"name\":\"FOID\",\"namespace\":\"sysflow.type\",\"size\":20,\"type\":\"fixed\"}]"
}

func (_ *UnionNullFOID) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullFOID) SetLong(v int64) {

	r.UnionType = (UnionNullFOIDTypeEnum)(v)
}

func (r *UnionNullFOID) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		return &FOIDWrapper{Target: (&r.FOID)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullFOID) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullFOID) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullFOID) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFOID) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullFOID) Finalize()                        {}

func (r *UnionNullFOID) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullFOIDTypeEnumFOID:
		return json.Marshal(map[string]interface{}{"sysflow.type.FOID": r.FOID})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullFOID")
}

func (r *UnionNullFOID) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["sysflow.type.FOID"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FOID)
	}
	return fmt.Errorf("invalid value for *UnionNullFOID")
}
