// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum int

const (
	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumSFHeader UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 0

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumContainer UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 1

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcess UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 2

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFile UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 3

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcessEvent UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 4

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkFlow UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 5

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileFlow UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 6

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileEvent UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 7

	UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkEvent UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum = 8
)

type UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent struct {
	SFHeader     *SFHeader
	Container    *Container
	Process      *Process
	File         *File
	ProcessEvent *ProcessEvent
	NetworkFlow  *NetworkFlow
	FileFlow     *FileFlow
	FileEvent    *FileEvent
	NetworkEvent *NetworkEvent
	UnionType    UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum
}

func writeUnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent(r *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumSFHeader:
		return writeSFHeader(r.SFHeader, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumContainer:
		return writeContainer(r.Container, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcess:
		return writeProcess(r.Process, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFile:
		return writeFile(r.File, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcessEvent:
		return writeProcessEvent(r.ProcessEvent, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkFlow:
		return writeNetworkFlow(r.NetworkFlow, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileFlow:
		return writeFileFlow(r.FileFlow, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileEvent:
		return writeFileEvent(r.FileEvent, w)
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkEvent:
		return writeNetworkEvent(r.NetworkEvent, w)
	}
	return fmt.Errorf("invalid value for *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent")
}

func NewUnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent() *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent {
	return &UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent{}
}

func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetString(v string) {
	panic("Unsupported operation")
}
func (r *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetLong(v int64) {
	r.UnionType = (UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnum)(v)
}
func (r *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) Get(i int) types.Field {
	switch i {
	case 0:
		r.SFHeader = NewSFHeader()
		return r.SFHeader
	case 1:
		r.Container = NewContainer()
		return r.Container
	case 2:
		r.Process = NewProcess()
		return r.Process
	case 3:
		r.File = NewFile()
		return r.File
	case 4:
		r.ProcessEvent = NewProcessEvent()
		return r.ProcessEvent
	case 5:
		r.NetworkFlow = NewNetworkFlow()
		return r.NetworkFlow
	case 6:
		r.FileFlow = NewFileFlow()
		return r.FileFlow
	case 7:
		r.FileEvent = NewFileEvent()
		return r.FileEvent
	case 8:
		r.NetworkEvent = NewNetworkEvent()
		return r.NetworkEvent
	}
	panic("Unknown field index")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) Finalize() {
}

func (r *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumSFHeader:
		return json.Marshal(map[string]interface{}{"SFHeader": r.SFHeader})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumContainer:
		return json.Marshal(map[string]interface{}{"Container": r.Container})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcess:
		return json.Marshal(map[string]interface{}{"Process": r.Process})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFile:
		return json.Marshal(map[string]interface{}{"File": r.File})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumProcessEvent:
		return json.Marshal(map[string]interface{}{"ProcessEvent": r.ProcessEvent})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkFlow:
		return json.Marshal(map[string]interface{}{"NetworkFlow": r.NetworkFlow})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileFlow:
		return json.Marshal(map[string]interface{}{"FileFlow": r.FileFlow})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumFileEvent:
		return json.Marshal(map[string]interface{}{"FileEvent": r.FileEvent})
	case UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEventTypeEnumNetworkEvent:
		return json.Marshal(map[string]interface{}{"NetworkEvent": r.NetworkEvent})
	}
	return nil, fmt.Errorf("invalid value for *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent")
}

func (r *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["SFHeader"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.SFHeader)
	}
	if value, ok := fields["Container"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Container)
	}
	if value, ok := fields["Process"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Process)
	}
	if value, ok := fields["File"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.File)
	}
	if value, ok := fields["ProcessEvent"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.ProcessEvent)
	}
	if value, ok := fields["NetworkFlow"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.NetworkFlow)
	}
	if value, ok := fields["FileFlow"]; ok {
		r.UnionType = 6
		return json.Unmarshal([]byte(value), &r.FileFlow)
	}
	if value, ok := fields["FileEvent"]; ok {
		r.UnionType = 7
		return json.Unmarshal([]byte(value), &r.FileEvent)
	}
	if value, ok := fields["NetworkEvent"]; ok {
		r.UnionType = 8
		return json.Unmarshal([]byte(value), &r.NetworkEvent)
	}
	return fmt.Errorf("invalid value for *UnionSFHeaderContainerProcessFileProcessEventNetworkFlowFileFlowFileEventNetworkEvent")
}
