// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     SysFlow.avsc
 */
package sfgo

import (
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/vm"
)

  
type SFObjectState int32

const (

	SFObjectStateCREATED SFObjectState = 0

	SFObjectStateMODIFIED SFObjectState = 1

	SFObjectStateREUP SFObjectState = 2

)

func (e SFObjectState) String() string {
	switch e {

	case SFObjectStateCREATED:
		return "CREATED"

	case SFObjectStateMODIFIED:
		return "MODIFIED"

	case SFObjectStateREUP:
		return "REUP"

	}
	return "unknown"
}

func writeSFObjectState(r SFObjectState, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewSFObjectStateValue(raw string) (r SFObjectState, err error) {
	switch raw {

	case "CREATED":
		return SFObjectStateCREATED, nil

	case "MODIFIED":
		return SFObjectStateMODIFIED, nil

	case "REUP":
		return SFObjectStateREUP, nil

	}

	return -1, fmt.Errorf("invalid value for SFObjectState: '%s'", raw)
}
